version: "3.9"

services:
  api:
    depends_on:
      - db
    build: ./api
    ports:
      - "8080:${API_PORT}"
    restart: unless-stopped
    env_file:
      - .env

  db:
    build: ./db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PORT}"
    env_file:
      - .env



volumes:
  db_data: